id: IE5AC45F3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T18:44:08+00:00'
last_modified: '2022-06-08T01:54:28.943077+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN524
  title: དབུ་མ་རྩ་ཤེས་ཀྱི་འགྲེལ་པ་བུདྡྷ་པཱ་ལི་ཏ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9C3C:
      image_group_id: I3CN8626
      title: ''
      total_pages: 224
      order: 1
      base_file: 9C3C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
