id: P004555
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN524
  title: དབུ་མ་རྩ་ཤེས་ཀྱི་འགྲེལ་པ་བུདྡྷ་པཱ་ལི་ཏ།
  author: ''
  volumes:
    0e96eef7d475453facaa2b5adba41b9e:
      image_group_id: I3CN8626
      title: ''
      volume_number: 1
      total_pages: 224
      base_file: v001.txt
